services:
    camera-uploader:
        build: .
        container_name: camera-uploader
        restart: unless-stopped
        privileged: true
        devices:
            - /dev/gpiomem
            - /dev/gpiochip0
            - /dev/gpiochip1
        environment:
            IMMICH_URL: https://immich.ehlers-thorsen.dk
            TZ: Europe/Copenhagen
        secrets:
            - "immich_api_key"
        volumes:
            - ./images:/images
            - /run/udev:/run/udev:ro
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ./config.json:/camera/config.json:ro

secrets:
    immich_api_key:
        file: ./secrets/immich_api_key.txt
